name: Build on Tag

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
         fetch-depth: 0  # 将fetch-depth设置为0，以仅拉取最新版本的仓库

    - name: fix error
      run:|
         git config --global user.name "yipiaoerguo"
         git config --global user.email "2182994665@qq.com"

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Dark-Ages-Último
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r383902, aosp-clang/android11-release/clang-r383902/binutils
        defconfig: camellia_defconfig
        image: Image.gz

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }} 
        tag: 3
